#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS)          += sensors_core.o

# accelerometer_sensor
obj-$(CONFIG_SENSORS_K2HH)          += k2hh.o
# optical_sensor
obj-$(CONFIG_SENSORS_TCS3490)	    += tcs3490.o
obj-$(CONFIG_SENSORS_CM3323)	    += cm3323.o
obj-$(CONFIG_SENSORS_CM36672P)      += cm36672p.o
obj-$(CONFIG_SENSORS_STK3013)      += stk3013.o
# grip_sensor
obj-$(CONFIG_SENSORS_SX9500)        +=sx9500.o
obj-$(CONFIG_SENSORS_SX9500_WIFI)   +=sx9500_wifi.o
